# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["jim@rainville.net"]
cloned_from = "https://github.com/fastly/compute-starter-kit-rust-default"
description = "Appliction for scoreboard using fanout"
language = "rust"
manifest_version = 3
name = "scoreboard"
service_id = "DQ72hW6l5ykcujJgJ148h4"

[scripts]
  build = "cargo build --bin fastly-compute-project --release --target wasm32-wasi --color always"
